In [62]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [139]:
books = pd.read_excel("C:/Users/jb24d625/OneDrive/Doktorat/CAS/Modul 6/book_recommender/archive (1)/Amazon_Books_Scraping/Books_df.xlsx")

In [140]:
print(books.head())

                                               Title               Author  \
0              The Complete Novel of Sherlock Holmes   Arthur Conan Doyle
1  Black Holes (L) : The Reith Lectures [Paperbac...      Stephen Hawking
2                                    The Kite Runner      Khaled Hosseini
3  Greenlights: Raucous stories and outlaw wisdom...  Matthew McConaughey
4  The Science of Storytelling: Why Stories Make ...           Will Storr

                 Main Genre           Sub Genre            Type      Price  \
0  Arts, Film & Photography  Cinema & Broadcast       Paperback  â‚¹169.00
1  Arts, Film & Photography  Cinema & Broadcast       Paperback   â‚¹99.00
2  Arts, Film & Photography  Cinema & Broadcast  Kindle Edition  â‚¹175.75
3  Arts, Film & Photography  Cinema & Broadcast       Paperback  â‚¹389.00
4  Arts, Film & Photography  Cinema & Broadcast       Paperback  â‚¹348.16

   Rating  No. of People rated  \
0     4.4                19923
1     4.5                 7686
2     4.6                50016
3     4.6                32040
4     4.5                 1707

                                                URLs
0  https://www.amazon.in/Complete-Novels-Sherlock...
1  https://www.amazon.in/Black-Holes-Lectures-Ste...
2  https://www.amazon.in/Kite-Runner-Khaled-Hosse...
3  https://www.amazon.in/Greenlights-Raucous-stor...
4  https://www.amazon.in/Science-Storytelling-Wil...

In [141]:
books

,Title,Author,Main Genre,Sub Genre,Type,Price,Rating,No. of People rated,URLs
0,The Complete Novel of Sherlock Holmes,Arthur Conan Doyle,"Arts, Film & Photography",Cinema & Broadcast,Paperback,â‚¹169.00,4.4,19923,https://www.amazon.in/Complete-Novels-Sherlock...
1,Black Holes (L) : The Reith Lectures [Paperbac...,Stephen Hawking,"Arts, Film & Photography",Cinema & Broadcast,Paperback,â‚¹99.00,4.5,7686,https://www.amazon.in/Black-Holes-Lectures-Ste...
2,The Kite Runner,Khaled Hosseini,"Arts, Film & Photography",Cinema & Broadcast,Kindle Edition,â‚¹175.75,4.6,50016,https://www.amazon.in/Kite-Runner-Khaled-Hosse...
3,Greenlights: Raucous stories and outlaw wisdom...,Matthew McConaughey,"Arts, Film & Photography",Cinema & Broadcast,Paperback,â‚¹389.00,4.6,32040,https://www.amazon.in/Greenlights-Raucous-stor...
4,The Science of Storytelling: Why Stories Make ...,Will Storr,"Arts, Film & Photography",Cinema & Broadcast,Paperback,â‚¹348.16,4.5,1707,https://www.amazon.in/Science-Storytelling-Wil...
...,...,...,...,...,...,...,...,...,...
7897,Insight Guides Poland (Travel Guide with Free ...,Insight Travel Guide,Travel,Travel & Holiday Guides,Paperback,"â‚¹1,326.00",4.7,16,https://www.amazon.in/Insight-Guides-Poland-Tr...
7898,Lonely Planet India 19 (Travel Guide),Anirban Mahapatra,Travel,Travel & Holiday Guides,Paperback,â‚¹850.00,4.4,187,https://www.amazon.in/Lonely-Planet-India-Trav...
7899,Eyewitness Travel Phrase Book French (EW Trave...,DK,Travel,Travel & Holiday Guides,Paperback,â‚¹307.00,4.5,168,https://www.amazon.in/Eyewitness-Travel-Phrase...
7900,Lonely Planet Australia (Travel Guide),Andrew Bain,Travel,Travel & Holiday Guides,Kindle Edition,"â‚¹1,814.50",4.7,267,https://www.amazon.in/Lonely-Planet-Australia-...
7901,Political Map of India Latest Map of India Wit...,Wonder House Books,Travel,Travel & Holiday Guides,Poster,â‚¹99.00,3.9,48,https://www.amazon.in/Political-Map-India-Terr...

In [142]:
#remove Type, Price and URLs
books = books.drop(columns = "Type")
books = books.drop(columns = "Price")
books = books.drop(columns = "URLs")

#remove duplicates
books = books.drop_duplicates(subset='Title')

In [143]:
#rename columns for cleaner code
books.rename(columns={
    'Title': 'title',
    'Author': 'author',
    'Main Genre': 'main_genre',
    'Sub Genre': 'sub_genre',
    'Rating': 'average_rating',
    'No. of People rated': 'ratingsCount'
}, inplace=True)

In [144]:
print(books.columns)

Index(['title', 'author', 'main_genre', 'sub_genre', 'average_rating',
       'ratingsCount'],
      dtype='object')

In [145]:
#Check datatypes
books.dtypes

title              object
author             object
main_genre         object
sub_genre          object
average_rating    float64
ratingsCount        int64
dtype: object

In [146]:
#we want to build a simple TF-IDF recommendation system so we need strings for text columns instead of objects and combine them to one column
books['content'] = (
    books['title'].astype(str) + " " +
    books['author'].astype(str) + " " +
    books['main_genre'].astype(str) + " " +
    books['sub_genre'].astype(str)
)

In [147]:
books.dtypes

title              object
author             object
main_genre         object
sub_genre          object
average_rating    float64
ratingsCount        int64
content            object
dtype: object

In [148]:
#pandas often uses object as generic term, so we test whether string worked even though it does not say string
print(type(books['content'].iloc[0]))

<class 'str'>

In [149]:
#check missing data
books.isnull()

,title,author,main_genre,sub_genre,average_rating,ratingsCount,content
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
7897,False,False,False,False,False,False,False
7898,False,False,False,False,False,False,False
7899,False,False,False,False,False,False,False
7900,False,False,False,False,False,False,False
7901,False,False,False,False,False,False,False

TF-IDF

In [153]:
#TF is the term frequency which shows how often a word appears in the strings of the content column
#IDF is the inverse document frequency that shows how rare the word is across all books
#I use the stop words from the english language to remove useless words like the, and, is etc. 

vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(books['content'])

In [154]:
print("TF-IDF shape:", tfidf_matrix.shape)

TF-IDF shape: (5722, 12643)

In [155]:
#I use cosine similarity to compare every book with every other book. 1.0 = identical 0.0 = completely different
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [156]:
#map the titles to drop books that are duplicates
indices = pd.Series(books.index, index=books['title'])

In [157]:
#recommendation function, given a book name system returns 5 top similar books
#index given so that I can access the book and check the cosine similarity of this book with all other books
def recommend_books(title, top_n=5): 
    if title not in indices: 
        return f"Book '{title}' not found." 
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]
    book_indices = [i[0] for i in sim_scores]

    return books[['title', 'author', 'main_genre']].iloc[book_indices]

In [158]:
#test
book_name = "Fantastic Beasts and Where to Find Them: The Original Screenplay"
print("\nRecommendations:\n") 
print(recommend_books(book_name))

Recommendations:

                                                title        author  \
6   Fantastic Beasts: The Crimes of Grindelwald - ...  J.K. Rowling
23  FANTASTIC BEASTS: THE SECRETS OF DUMBLEDORE ï¿...  J.K. Rowling
9                                          Screenplay     Syd Field
40                                               Will    Will Smith
33  The Magic of MinaLima: Celebrating the Graphic...      MinaLima

                  main_genre
6   Arts, Film & Photography
23  Arts, Film & Photography
9   Arts, Film & Photography
40  Arts, Film & Photography
33  Arts, Film & Photography

Embedded Vector Recommender with Ratings

In [159]:
#used to base the recommendation on semantic similarity instead of cosine similarity
#import additional library to convert text to embeddings
!pip install sentence-transformers

from sentence_transformers import SentenceTransformer

Requirement already satisfied: sentence-transformers in c:\anaconda\lib\site-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (5.7.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (1.13.0)
Requirement already satisfied: torch>=1.11.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (2.9.0)
Requirement already satisfied: numpy>=1.20.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (1.4.2)
Requirement already satisfied: scipy>=1.0.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (4.12.2)
Requirement already satisfied: tqdm>=4.0.0 in c:\anaconda\lib\site-packages (from sentence-transformers) (4.66.4)
Requirement already satisfied: filelock>=3.10.0 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2024.3.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.1)
Requirement already satisfied: typer in c:\anaconda\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.9.0)
Requirement already satisfied: joblib>=1.2.0 in c:\anaconda\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\anaconda\lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (2.2.0)
Requirement already satisfied: sympy>=1.13.3 in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\anaconda\lib\site-packages (from torch>=1.11.0->sentence-transformers) (69.5.1)
Requirement already satisfied: colorama in c:\anaconda\lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: regex>=2025.10.22 in c:\anaconda\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\anaconda\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\anaconda\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.2.0)
Requirement already satisfied: certifi in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\anaconda\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\anaconda\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\anaconda\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\anaconda\lib\site-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.1.7)
Requirement already satisfied: sniffio>=1.1 in c:\anaconda\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.3.0)

In [160]:
#load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(books['content'].tolist())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [161]:
#cosine similarity
cosine_sim = cosine_similarity(embeddings, embeddings)

In [162]:
#weighted rating for a hybrid recommender system
C = books['average_rating'].mean() 
m = books['ratingsCount'].quantile(0.75) 

def weighted_rating(x, m=m, C=C): 
    v = x['ratingsCount'] 
    R = x['average_rating'] 
    return (v / (v + m)) * R + (m / (v + m)) * C 
    
books['score'] = books.apply(weighted_rating, axis=1)

In [163]:
#first you find the index of the book you want
#then you get the similarity scores and sort them with the most similar books first
def hybrid_recommend(title, top_n=10):

    if title not in indices: 
        return f"books '{title}' not found." 

    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx])) 
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:50]
    book_indices = [i[0] for i in sim_scores]
    candidates = books.iloc[book_indices].copy()
    candidates['similarity'] = [i[1] for i in sim_scores]
    candidates['norm_score'] = candidates['score'] / candidates['score'].max()
    candidates['final_score'] = (
        0.7 * candidates['similarity'] +
        0.3 * candidates['norm_score']
    )
    candidates = candidates.sort_values('final_score', ascending=False)

    return candidates[['title', 'author', 'main_genre','average_rating', 'ratingsCount']].head(top_n)

In [164]:
#test
book_name = "Fantastic Beasts and Where to Find Them: The Original Screenplay"
print("\nRecommendations:\n") 
print(hybrid_recommend(book_name))

Recommendations:

                                                  title         author  \
6     Fantastic Beasts: The Crimes of Grindelwald - ...   J.K. Rowling
23    FANTASTIC BEASTS: THE SECRETS OF DUMBLEDORE ï¿...   J.K. Rowling
33    The Magic of MinaLima: Celebrating the Graphic...       MinaLima
100   Harry Potter and the Cursed Child - Parts One ...   J.K. Rowling
900             Harry Potter and the Chamber of Secrets   J.K. Rowling
962                Harry Potter and the Deathly Hallows   J.K. Rowling
897            Harry Potter and the Philosopher's Stone   J.K. Rowling
961           Harry Potter and the Order of the Phoenix   J.K. Rowling
7737          Harry Potter - The Illustrated Collection  J. K. Rowling
903                 Harry Potter and the Goblet of Fire   J.K. Rowling

                    main_genre  average_rating  ratingsCount
6     Arts, Film & Photography             4.6         10152
23    Arts, Film & Photography             4.6          1280
33    Arts, Film & Photography             4.8           595
100   Arts, Film & Photography             4.4         86578
900           Children's Books             4.7         86490
962           Children's Books             4.8         87027
897           Children's Books             4.7        107802
961           Children's Books             4.7         66771
7737        Teen & Young Adult             4.8           691
903           Children's Books             4.8         67626